name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: [4.4]  # More stable version for CI/CD

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Ensure full repo is cloned

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 🛑 Fix: Stop any old MongoDB instances before starting
    - name: Stop old MongoDB instances (if any)
      run: |
        sudo systemctl stop mongod || true
        docker stop $(docker ps -q --filter ancestor=mongo) || true
        docker rm $(docker ps -aq --filter ancestor=mongo) || true

    # ✅ Fix: Use a different MongoDB port to avoid conflicts
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: "4.4"
        mongodb-port: 27018  # Change port to avoid conflicts

    # ⏳ Fix: Wait longer to allow MongoDB to start
    - name: Wait for MongoDB to start
      run: sleep 20s  # Increased from 10s to 20s

    # 🔍 Fix: Debug MongoDB status if it fails
    - name: Check MongoDB Status
      run: ps aux | grep mongo

    - name: Install dependencies
      run: npm ci

    - name: Run backend tests
      run: npm test
      env:
        CI: true
        MONGODB_URI: mongodb://localhost:27018/test  # Updated port
        JWT_SECRET: test_secret
        NODE_ENV: test

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage/

    - name: Run integration tests
      run: npm run test:integration
      env:
        CI: true
        MONGODB_URI: mongodb://localhost:27018/test
        JWT_SECRET: test_secret
        NODE_ENV: test
