name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: [4.4]  # Stable for CI/CD

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Ensures the full repo is cloned

    - name: Print Current Directory
      run: pwd && ls -la

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Wait for MongoDB to start
      run: sleep 10s

    - name: Install dependencies (Backend)
      run: npm ci
      working-directory: backend  # Change this if your package.json is in a different folder

    - name: Install frontend dependencies (If Exists)
      run: |
        if [ -d "frontend" ]; then cd frontend && npm ci; fi

    - name: Run backend tests
      run: npm test
      env:
        CI: true
        MONGODB_URI: mongodb://localhost:27017/test
        JWT_SECRET: test_secret
        NODE_ENV: test
      working-directory: backend  # Ensure it runs in the correct directory

    - name: Run frontend tests (If Exists)
      working-directory: ./frontend
      run: |
        if [ -d "frontend" ]; then npm test; fi
      env:
        CI: true

    - name: Build check
      run: |
        npm run build
        if [ -d "frontend" ]; then cd frontend && npm run build; fi

    - name: Ensure Coverage Directories Exist
      run: |
        mkdir -p coverage
        mkdir -p frontend/coverage

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: |
          coverage/
          frontend/coverage/

    - name: Run integration tests
      run: npm run test:integration
      env:
        CI: true
        MONGODB_URI: mongodb://localhost:27017/test
        JWT_SECRET: test_secret
        NODE_ENV: test
      working-directory: backend  # Adjust if needed

    - name: Check for npm vulnerabilities
      run: |
        npm audit --audit-level=critical || echo "Ignoring non-critical vulnerabilities"
        if [ -d "frontend" ]; then cd frontend && npm audit --audit-level=critical || echo "Ignoring non-critical vulnerabilities"; fi
