name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Ensures the full repo is cloned

      - name: Debug Directory Structure
        run: pwd && ls -la && ls -la backend  # ✅ Prints structure for debugging

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install backend dependencies
        working-directory: backend  # ✅ Runs in the correct directory
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run backend tests
        working-directory: backend  # ✅ Ensures tests run in the correct folder
        run: npm test
        env:
          CI: true
          MONGODB_URI: mongodb://localhost:27017/test
          JWT_SECRET: test_secret
          NODE_ENV: test
